# Settings for Table 'campaign'
# Just list the columns and their settings
campaign:
  id:
    title: ID
    showInOverview: true
  status:
    showInOverview: true
    description: Mit einer Änderung hier, kannst du beeinflussen in welcher Phase die Kampagne ist.
    source: staticValues
    editElement: select
    values:
      1: Disabled
      2: Waiting for Publishing
      3: Published
      4: Influencer Selection
      5: Placement in Production
      6: Finished
      7: Not Completed
      8: Deleted
  brand_id:
    showInOverview: true
    title: Marken Account
    editElement: select
    source: otherTable
    table_name: brand
    table_key: id
    table_column: brand_name
  description:
    editElement: textarea
  pro_bono:
    editElement: checkbox
  created:
    showInOverview: true
  modified:
    showInOverview: true