# Settings for Table 'campaign'
# Just list the columns and their settings
campaign:
  id:
    title: ID
    showInOverview: true
  status:
    showInOverview: true
    description: Mit einer Änderung hier, kannst du beeinflussen in welcher Phase die Kampagne ist.
    source: staticValues
    editElement: select
    values:
      1: Disabled
      2: Waiting for Publishing
      3: Published
      4: Influencer Selection
      5: Placement in Production
      6: Finished
      7: Not Completed
      8: Deleted
  brand_id:
    showInOverview: true
    title: Marken Account
    editElement: select
    source: otherTable
    table_name: brand
    table_key: id
    table_column: brand_name
  brand_name:
    showInOverview: true
    editElement: input
  product_name:
    showInOverview: true
    editElement: input
  created:
    showInOverview: true
  modified:
    showInOverview: true
  url:
    editElement: input
  dos:
    editElement: inputArray
  donts:
    editElement: inputArray
  ig_tag:
    editElement: input
  ig_person:
    editElement: input
  yt_tag:
    editElement: input
  yt_url:
    editElement: input
  logo:
    editElement: input
  edit_status:
    editElement: inputNumber
  edit_max:
    editElement: inputNumber
  application_deadline:
    editElement: input
  influencer_selection:
    editElement: input
  release_date:
    editElement: input
  age_categories:
    editElement: checkboxes
  gender_categories:
    editElement: checkboxes
  vertical_categories:
    editElement: checkboxes